[package]
name = "game_modding_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach2 = "0.4.2"
sysinfo = "0.30.5"
process-memory = "0.5.0"